apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app 
    spec:
      containers:
      - name: app-container
        image: eu.gcr.io/<PROJECT-ID-HERE>/app-container:v1.7
        env:
        - name: IMAGE_DIR
          value: /images
        volumeMounts:
        - mountPath: /images
          name: shared-images

      - name: sidecar-container
        image: eu.gcr.io/<PROJECT-ID-HERE>/sidecar-container:v1.6
        env:
        - name: IMAGE_DIR
          value: /images
        volumeMounts:
        - mountPath: /images
          name: shared-images

      volumes:
      - name: shared-images
        emptyDir: {}
