apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app
spec:
  containers:
  - name: app-container
    image: eu.gcr.io/<PROJECT-ID>/app-container:v1.3
    env:
    - name: IMAGE_DIR
      value: /images
    volumeMounts:
    - mountPath: /images
      name: shared-images

  - name: sidecar-container
    image: eu.gcr.io/<PROJECT-ID>/sidecar-container:v1.1
    env:
    - name: IMAGE_DIR
      value: /images
    volumeMounts:
    - mountPath: /images
      name: shared-images

  volumes:
  - name: shared-images
    emptyDir: {}
