apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  # - name: https
  #   port: 443
  #   targetPort: 3000
  #   protocol: TCP
  selector:
    app: app
  type: LoadBalancer
